{}.GetSteppablePipeline.OverloadDefinitions.Add.ToString( "C:\Users\uname\CAPTIVE_DEV\PASSIVE\GALAXY__WORKFLOW__CAPTIVE\$mpath\$GALAXY.txt" )
           Start-Job -DefinitionName $mpath.ToType.MemberType.value__.ToString.Equals.{
            ...
         Invoke.OverloadDefinitions.SyncRoot.GetType.Equals.Equals.Equals.OverloadDefinitions} {
            ...  
       SyncRoot.Equals.Equals-Type} {
            ...
     InvokeWithContext-PipelineVariable} {("
            ...   
   InvokeReturnAsIs('.Equals.Equals.Equals')")} {
            ...   
 GetHashCode.Value.Equals.Equals.Equals..{$mpath.Insert.Value.Name.Equals.Equals.Equals.OverloadDefinitions.IsReadOnly.Equals.IsInstance.Equals.TypeNameOfValue-clike(*)-like ($mpath *$GALAXY*"char*".ToLowerInvariant("GALAXY"))}}
            ...
$env:PSModulePath = {
            ...
is.valueOf-clike*$PSSessionConfigurationName.CopyTo($GALAXY)-inotmatch{get};===__--__ [${GALAXY}]  {
 .Equals.Equals.Equals LET => | ==> |  ===-clike__#[*"&&"####******"&"*****####"&&"*]}}