Invoke-WebRequest -Uri Invoke-WebRequest -Uri "https://cs50.readthedocs.io/SECRET" -Headers @{
"method"="POST"
  "authority"="cs50.readthedocs.io"
  "scheme"="https"
  "path"="//..//SECRET"//..//"
  "pragma"="n-Headers @{
"method"="POST"
  "authority"="cs50.readthedocs.io"
  "scheme"="https"
  "path"="//..//SECRET"//..//"
  "pragma"="n
  o-cache"
  "cache-control"="no-cache"
  "upgrade-insecure-requests"="1"
  "user-agent"="Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36"
  "accept"="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
  "sec-fetch-site"="none"
  "sec-fetch-mode"="navigate"
  "sec-fetch-user"="?1"
  "sec-fetch-dest"="document"
  "accept-encoding"="gzip, deflate, br"
  "accept-language"="en-US,en;q=0.9"
  "cookie"="_ga=GA1.3.2100862629.1605654619; _gid=GA1.3.551233137.1605654619"
}


COM