#IMPORT ===>>>$_$$___OS___$$_$ {


#IMPORT <...STDIO>


#IMPORT [ "PYTHON7" ]




{(["******######////&& ++ 
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**"{(#""****&&&&****""#)}
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**"{(#""****&&&&****""#)}
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**"?ISTrue!=("false").get.LastIndexOfAny.Replace.Clone.Length().Equals #1#
{(#""****&&&&****""#)}\
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**\"\{(#""****&&&&****""#)}\
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**\"\{(#""****&&&&****""#)}\
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**\"\{(#""****&&&&****""#)}\
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**\"\{(#""****&&&&****""#)}\
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
$ENV:SMS_ADMIN_UI_PATH="{([&**&&**\"\{(#""****&&&&****""#)}\
...
++1__{*.*]0)*}

||__{}__)))*&* var_char*| ==> {
$ENV:SMS_ADMIN_UI_PATH
}||
######****** ++m &&" ])}